### ISSUE TITLE
关于几个算法名称

### ISSUE THREAD

**Issue by mumaba** [snail1996/InfluenceMaximization#1]
你好。
OPT算法，和CCA算法  分别是那2个算法。可以告知一下嘛？谢谢。
DCA算法，应该是Degreecount算法把。

**Comment by snail1996** [comment]
不好意思，没及时看邮箱。OPT算法是自己取的名字，为优化算法，对启发式算法的种子集合进行蒙特卡罗贪心优化。CCA算法是曹玖新教授的一篇里提到的算法。DCA算法也是我自己取的名字。这个是上曹玖新教授的复杂网络课程的大作业，有一定的出题背景。







在 2021-02-03 19:05:37，"mumaba" <notifications@github.com> 写道：

你好。
OPT算法，和CCA算法 分别是那2个算法。可以告知一下嘛？
DCA算法，应该是Degreecount算法把。

**Comment by mumaba** [comment]
我知道了，非常感谢，谢谢  ！
